# irc_helpers should/must always be first.
modules = (
    'irc_helpers',
    'cron',
    'webserver',
    'core',
    'datastore',
    'security',
    'chantrack',
    'chanmanage',
    'ctcp',
    'zmachine',
    'rss',
    'logger',
    'dynamic',
    'pisg',
    'quotes',
    'driving',
    'reference',
    'supposedlyfunny',
    'datastoreirc',
    'todo',
    #'lastfm',
    #'irclogger'
)